In [39]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [24]:
X = np.arange(15).reshape(-1,1)
y = np.array([0,0,0,0,0,0,0,1,0,1,1,1,1,1,1])

X, y

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1]))

In [25]:
model = LogisticRegression(C=0.5)
model.fit(X, y)

LogisticRegression(C=0.5)

In [26]:
model.classes_

array([0, 1])

In [27]:
model.intercept_

array([-5.96039406])

In [28]:
model.coef_

array([[0.7944447]])

In [29]:
model.predict_proba(X)

array([[0.99742774, 0.00257226],
       [0.99432475, 0.00567525],
       [0.98752536, 0.01247464],
       [0.9728026 , 0.0271974 ],
       [0.94172912, 0.05827088],
       [0.87954946, 0.12045054],
       [0.76740677, 0.23259323],
       [0.59851494, 0.40148506],
       [0.40247491, 0.59752509],
       [0.23332901, 0.76667099],
       [0.12088746, 0.87911254],
       [0.05849725, 0.94150275],
       [0.02730655, 0.97269345],
       [0.01252546, 0.98747454],
       [0.00569853, 0.99430147]])

In [30]:
y_pred = model.predict(X)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [33]:
model.score(X, y)

0.8666666666666667

In [37]:
confusion_matrix(y, y_pred)


array([[7, 1],
       [1, 6]], dtype=int64)

In [40]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88         8
           1       0.86      0.86      0.86         7

    accuracy                           0.87        15
   macro avg       0.87      0.87      0.87        15
weighted avg       0.87      0.87      0.87        15



> Handwritten Dataset


In [45]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits

In [46]:
X, y = load_digits(return_X_y = True)

In [49]:
X[0], y

(array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]),
 array([0, 1, 2, ..., 8, 9, 8]))

In [52]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 10)

> Standardisation

In [66]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

-- Training the model

In [67]:
model = LogisticRegression(C=0.05, multi_class='ovr', random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0)

In [68]:
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

In [71]:
model.score(X_train, y_train)

0.9737470167064439

In [72]:
model.score(X_test, y_test)

0.9537037037037037

In [73]:
confusion_matrix(y_test, y_pred)

array([[50,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 53,  2,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0, 55,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 53,  0,  0,  0,  1,  2,  0],
       [ 0,  0,  0,  0, 49,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0, 49,  0,  0,  0,  2],
       [ 0,  1,  0,  0,  0,  0, 54,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 59,  0,  0],
       [ 0,  2,  1,  0,  0,  1,  2,  0, 43,  1],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  2, 50]], dtype=int64)

In [75]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        51
           1       0.95      0.93      0.94        57
           2       0.95      1.00      0.97        55
           3       1.00      0.95      0.97        56
           4       0.96      0.96      0.96        51
           5       0.96      0.96      0.96        51
           6       0.96      0.98      0.97        55
           7       0.97      0.98      0.98        60
           8       0.84      0.86      0.85        50
           9       0.94      0.93      0.93        54

    accuracy                           0.95       540
   macro avg       0.95      0.95      0.95       540
weighted avg       0.95      0.95      0.95       540

